# Use root/example as user/password credentials
version: '3.3'

services:

  Lian:
    image: mariadb:10.6 # mariadb 10.6 버전 이미지 사용
    container_name: BankApp of Lian # container 이름 설정
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: tkfkdgo12! # contatiner 생성 후 root의 비밀번호를 저장한 파일을 설정함으로 root 비밀번호를 설정
      MARIADB_DATABASE: springboot
      MARIADB_USER: Lian
      MARIADB_PASSWORD: tkfkdgo12!

      volumes:
        # - ./master_db/date:/var/lib/mysql
        # - ./master_db/config/:/etc/mysql/conf.d
    ports:
      - "3306:3306" # 이 옵션은 docker engine에게 각 container에게 포트를 수동으로 설정하게 해줍니다.